import polars as pl

SCHEMA = {
    # ---- strings ----
    "id_basica": pl.Utf8,
    "id_empresa": pl.Utf8,
    "id_tipo_linha": pl.Utf8,
    "id_arquivo": pl.Utf8,
    "id_di": pl.Utf8,
    "cd_di": pl.Utf8,
    "nr_ano_mes_referencia": pl.Utf8,
    "nr_chave": pl.Utf8,
    "nr_singular": pl.Utf8,
    # ---- ints ----
    "nr_decolagem": pl.Int8,
    "nr_mes_referencia": pl.Int16,
    "nr_dia_referencia": pl.Int8,
    "nr_voo": pl.Int16,
    "nr_semestre_referencia": pl.Int16,
    "nr_trimestre_referencia": pl.Int8,
    "nr_semana_referencia": pl.Int8,
    "nr_escala_destino": pl.Int16,
    # ---- floats (sem vírgula) ----
    "lt_combustivel": pl.Float16,
    "kg_payload": pl.Float16,
    "km_distancia": pl.Float16,
    "kg_bagagem_livre": pl.Float16,
    "kg_bagagem_excesso": pl.Float16,
    "kg_carga_paga": pl.Float16,
    "kg_carga_gratis": pl.Float16,
    "kg_correio": pl.Float16,
    "kg_peso": pl.Float16,
    "nr_pax_gratis_km": pl.Float16,
    "nr_carga_gratis_km": pl.Float16,
    "nr_correio_km": pl.Float16,
    "nr_bagagem_paga_km": pl.Float16,
    "nr_ask": pl.Float16,
    "nr_rpk": pl.Float16,
    "nr_atk": pl.Float16,
    "nr_rtk": pl.Float16,
    # ---- converter depois ----
    "nr_horas_voadas": pl.Utf8,
    "nr_velocidade_media": pl.Utf8,
    "nr_ano_partida_real": pl.Utf8,
    "nr_semestre_partida_real": pl.Utf8,
    "nr_trimestre_partida_real": pl.Utf8,
    "nr_assentos_ofertados": pl.Utf8,
    "nr_passag_pagos": pl.Utf8,
    "nr_passag_gratis": pl.Utf8,
    "nr_linha": pl.Utf8,
    "nr_carga_paga_km": pl.Utf8,
    "nr_bagagem_gratis_km": pl.Utf8,
}
